Install NumPy using pip:

In [1]:
pip install numpy


Importing NumPy

In [2]:
import numpy as np


Creating Arrays :

Creating 1-D array

In [3]:
# 1D array
arr_1d = np.array([1, 2, 3, 4])
print("1D Array:", arr_1d)




1D Array: [1 2 3 4]


In [4]:
# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr_2d)


2D Array:
 [[1 2 3]
 [4 5 6]]


In [5]:
# 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:\n", arr_3d)


3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Attributes

In [8]:
print("Shape:", arr_3d.shape)  # Shape of the array

Shape: (2, 2, 2)


In [9]:
print("Size:", arr_3d.size)    # Total elements
print("Data Type:", arr_3d.dtype)  # Data type of elements

Size: 8
Data Type: int64
