1. Creating Arrays from Lists :

Convert a Python list or tuple into a NumPy array using numpy.array():

In [1]:
import numpy as np

# From a list
arr1 = np.array([1, 2, 3, 4])
print(arr1)

# From a tuple
arr2 = np.array((5, 6, 7, 8))
print(arr2)


[1 2 3 4]
[5 6 7 8]


2. Arrays with Default Values
NumPy provides functions to create arrays with specific values or patterns.

Array of zeros:

In [2]:
zeros = np.zeros((2, 3))  # 2x3 array of zeros
print(zeros)


[[0. 0. 0.]
 [0. 0. 0.]]


Array of ones:

In [3]:
ones = np.ones((3, 4))  # 3x4 array of ones
print(ones)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Empty array (uninitialized values):

In [4]:
empty = np.empty((2, 3))  # 2x3 array with random values
print(empty)


[[0. 0. 0.]
 [0. 0. 0.]]


Identity matrix:

In [5]:
identity = np.eye(3)  # 3x3 identity matrix
print(identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3. Arrays with Ranges of Numbers:

Using arange():





In [6]:
arr_range = np.arange(0, 10, 2)  # Numbers from 0 to 10 with a step of 2
print(arr_range)


[0 2 4 6 8]


Using linspace():

In [7]:
lin_space = np.linspace(0, 1, 5)  # 5 equally spaced numbers between 0 and 1
print(lin_space)


[0.   0.25 0.5  0.75 1.  ]


4. Random Arrays

Generate random values for arrays.

Random floats:

In [8]:
rand = np.random.rand(3, 3)  # 3x3 array with random floats in [0, 1)
print(rand)


[[0.32007712 0.95042683 0.48008947]
 [0.18844107 0.75709301 0.45736387]
 [0.34871163 0.4474464  0.56761052]]


Random integers:

In [9]:
randint = np.random.randint(0, 10, (2, 3))  # 2x3 array of random integers between 0 and 9
print(randint)


[[6 5 8]
 [0 1 8]]


Checking Array Properties

In [10]:
print(arr1.shape)  # Shape of the array
print(arr1.ndim)   # Number of dimensions
print(arr1.size)   # Total number of elements
print(arr1.dtype)  # Data type of elements


(4,)
1
4
int64


In [11]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]
